spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb;MODE=MySQL;
    username: SA
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
#          kakao:
#            client-id: <your id>
#            client-secret: <your secret>
#            redirect-uri: <your url>/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#            scope:
#              - profile
#              - account_email
          google:
            client-id: 123905091561-t9neu7t8jf4bv9vot4cs7jr4sls0fuke.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 888ce812de65e1a1b88f6bf1ee8a43fe
            client-secret: Xw9Hg5WRjsrVBNOkDPF4d62VH45Hdtp1
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - account_email
          google:
            client-id: 123905091561-t9neu7t8jf4bv9vot4cs7jr4sls0fuke.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  redis:
    host: localhost
    port: 6379